version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: eaas_db
    environment:
      POSTGRES_USER: eaas
      POSTGRES_PASSWORD: eaas_dev
      POSTGRES_DB: eaas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
